Server:
  Port:
  RunMode: debug
Logger:
  filePath: ../logs/logs.log
  Encoding: json
  level: debug
cors:
  allowOrigins: "*"
postgres:
  host: postgres_container
  port: 5432
  user: postgres
  password: admin
  dbName: car_sale_db
  sslMode: false
redis:
  host: redis_container
  port: 6379
  password: password
  db: 0
  minIdleConnection: 100
  poolSize: 5000
  poolTimeout: 240
